/**
 * Migration for table: merchant_properties
 */
export async function up(pool) {
    console.log('Creating table: merchant_properties...');
    await pool.query(`
CREATE TABLE IF NOT EXISTS \`merchant_properties\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`user_id\` int DEFAULT NULL,
  \`admin_id\` int DEFAULT NULL,
  \`property_id\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`merchant_id\` int NOT NULL,
  \`merchant_package_id\` int DEFAULT NULL,
  \`category_id\` int DEFAULT NULL,
  \`property_code\` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`title\` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  \`description\` longtext COLLATE utf8mb4_general_ci,
  \`property_main_type\` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`property_sub_type\` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`property_type\` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`pg_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`listing_type\` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  \`property_segment\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`sale_price\` decimal(15,2) DEFAULT NULL,
  \`ownership_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Freehold, Leasehold, etc.',
  \`transaction_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'New Property, Resale',
  \`rent_price\` decimal(15,2) DEFAULT NULL,
  \`rent_negotiable\` tinyint(1) NOT NULL DEFAULT '0',
  \`security_deposit\` decimal(15,2) DEFAULT NULL,
  \`maintenance\` decimal(15,2) DEFAULT NULL,
  \`maintenance_included\` tinyint(1) NOT NULL DEFAULT '0',
  \`preferred_tenants\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`price_negotiable\` tinyint(1) DEFAULT '0',
  \`available_from\` date DEFAULT NULL,
  \`agreement_duration\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'e.g., 11 months, 2 years',
  \`notice_period\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'e.g., 1 month, 2 months',
  \`electricity_charges\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Excluded/Included',
  \`water_charges\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Excluded/Included',
  \`bedrooms\` int DEFAULT '0',
  \`flooring_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`facing\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`bathrooms\` int DEFAULT '0',
  \`balconies\` int DEFAULT '0',
  \`area_sqft\` decimal(10,2) DEFAULT NULL,
  \`carpet_area\` int DEFAULT NULL,
  \`built_up_area\` int DEFAULT NULL,
  \`land_area\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`furnishing_status\` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`possession_status\` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`age_of_property\` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`floors_total\` int DEFAULT NULL,
  \`floor_no\` int DEFAULT NULL,
  \`address_line1\` text COLLATE utf8mb4_general_ci,
  \`address_line2\` text COLLATE utf8mb4_general_ci,
  \`landmark\` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`city_id\` int DEFAULT NULL,
  \`state_id\` int DEFAULT NULL,
  \`country_id\` int DEFAULT NULL,
  \`locality_id\` int DEFAULT NULL,
  \`city\` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`state\` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`country\` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`pincode\` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`latitude\` decimal(10,7) DEFAULT NULL,
  \`longitude\` decimal(10,7) DEFAULT NULL,
  \`amenities\` text COLLATE utf8mb4_general_ci,
  \`status\` varchar(20) COLLATE utf8mb4_general_ci DEFAULT 'pending',
  \`featured\` tinyint(1) DEFAULT '0',
  \`views_count\` int DEFAULT '0',
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  \`area\` varchar(250) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`location\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`nearby_area\` varchar(191) COLLATE utf8mb4_general_ci NOT NULL,
  \`property_id_custom\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`total_beds\` int DEFAULT NULL,
  \`available_beds\` int DEFAULT NULL,
  \`room_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`food_facility\` tinyint(1) NOT NULL DEFAULT '0',
  \`gate_closing_time\` time DEFAULT NULL,
  \`laundry\` tinyint(1) NOT NULL DEFAULT '0',
  \`wifi\` tinyint(1) NOT NULL DEFAULT '0',
  \`lock_in_period\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`cabins\` int DEFAULT NULL,
  \`workstations\` int DEFAULT NULL,
  \`washrooms_private\` int DEFAULT NULL,
  \`washrooms_shared\` int DEFAULT NULL,
  \`loading_dock\` tinyint(1) NOT NULL DEFAULT '0',
  \`ceiling_height\` decimal(8,2) DEFAULT NULL,
  \`soil_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`water_source\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`road_access\` tinyint(1) NOT NULL DEFAULT '0',
  \`fencing_done\` tinyint(1) NOT NULL DEFAULT '0',
  \`distance_from_highway\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`plot_length\` decimal(10,2) DEFAULT NULL,
  \`plot_breadth\` decimal(10,2) DEFAULT NULL,
  \`corner_plot\` tinyint(1) NOT NULL DEFAULT '0',
  \`land_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Dry, Wet',
  \`authority_approved\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`rera_number\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`na_plot\` tinyint(1) NOT NULL DEFAULT '0',
  \`encumbrance_free\` tinyint(1) NOT NULL DEFAULT '0',
  \`approved_by\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`private_garden\` tinyint(1) NOT NULL DEFAULT '0',
  \`servant_room\` tinyint(1) NOT NULL DEFAULT '0',
  \`store_room\` tinyint(1) NOT NULL DEFAULT '0',
  \`frontage_width\` decimal(10,2) DEFAULT NULL,
  \`visibility_type\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Main Road, Mall',
  \`suitable_for\` varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Retail, Food, Office, Clinic',
  \`covered_area\` decimal(10,2) DEFAULT NULL,
  \`truck_entry\` tinyint(1) NOT NULL DEFAULT '0',
  \`road_width\` decimal(10,2) DEFAULT NULL,
  \`video_url\` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`property_age\` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  \`construction_start_date\` date DEFAULT NULL,
  \`possession_date\` date DEFAULT NULL,
  \`no_brokerage\` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`property_code\` (\`property_code\`),
  UNIQUE KEY \`merchant_properties_property_id_unique\` (\`property_id\`),
  KEY \`merchant_id\` (\`merchant_id\`),
  KEY \`category_id\` (\`category_id\`),
  KEY \`fk_property_package\` (\`merchant_package_id\`),
  KEY \`idx_listing_type\` (\`listing_type\`),
  KEY \`idx_property_type\` (\`property_main_type\`),
  KEY \`idx_city_locality\` (\`city_id\`,\`locality_id\`),
  KEY \`idx_price_sale\` (\`sale_price\`),
  KEY \`idx_price_rent\` (\`rent_price\`),
  KEY \`idx_bedrooms\` (\`bedrooms\`),
  KEY \`idx_city\` (\`city\`),
  KEY \`idx_area\` (\`area\`),
  CONSTRAINT \`fk_property_package\` FOREIGN KEY (\`merchant_package_id\`) REFERENCES \`admin_merchant_packages\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
    `);
}

export async function down(pool) {
    console.log('Dropping table: merchant_properties...');
    await pool.query('DROP TABLE IF EXISTS merchant_properties');
}
